<%@ Page Language="vb" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="admin_shipping.aspx.vb" Inherits="admin_shipping" Title="Shipping Rates" StylesheetTheme="White" Theme="White" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
	<h1>Shipping Calculator</h1>
	<asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
		AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="shippingRateID"
		DataSourceID="SqlDataSource1">
		<Columns>
			<asp:BoundField DataField="Service" HeaderText="Service" SortExpression="Service" />
			<asp:BoundField DataField="DollarsPerPound" HeaderText="Rate/lb." SortExpression="DollarsPerPound" />
		</Columns>
	</asp:GridView>
	<br />
	<h1>Add Shipping Rate</h1><br />
	<asp:FormView ID="FormView1" runat="server" DataKeyNames="shippingRateID" DataSourceID="SqlDataSource1"
		DefaultMode="Insert">
		 <InsertItemTemplate>
			Service<br />
			<asp:TextBox ID="ServiceTextBox" runat="server" Text='<%#Bind("Service")%>'>
			</asp:TextBox><br />
			Dollars Per Pound<br />
			<asp:TextBox ID="DollarsPerPoundTextBox" runat="server" Text='<%#Bind("DollarsPerPound")%>'>
			</asp:TextBox><br /><br />
			<asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert"
				Text="Insert">
			</asp:LinkButton>
		</InsertItemTemplate>
	</asp:FormView>
	<br />
	<br />
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
		DeleteCommand="DELETE FROM [CMRC_ShippingRates] WHERE [shippingRateID] = @shippingRateID"
		InsertCommand="INSERT INTO [CMRC_ShippingRates] ([Service], [DollarsPerPound]) VALUES (@Service, @DollarsPerPound)"
		SelectCommand="SELECT [shippingRateID], [Service], [DollarsPerPound] FROM [CMRC_ShippingRates]"
		UpdateCommand="UPDATE [CMRC_ShippingRates] SET [Service] = @Service, [DollarsPerPound] = @DollarsPerPound WHERE [shippingRateID] = @shippingRateID">
		<DeleteParameters>
			<asp:Parameter Name="shippingRateID" Type="Int32" />
		</DeleteParameters>
		<UpdateParameters>
			<asp:Parameter Name="Service" Type="String" />
			<asp:Parameter Name="DollarsPerPound" Type="Decimal" />
			<asp:Parameter Name="original_shippingRateID" Type="Int32" />
		</UpdateParameters>
		<InsertParameters>
			<asp:Parameter Name="Service" Type="String" />
			<asp:Parameter Name="DollarsPerPound" Type="Decimal" />
		</InsertParameters>
	</asp:SqlDataSource>
</asp:Content>

