<%@ Page Language="vb" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="admin_categories.aspx.vb" Inherits="admin_categories" Title="Product Categories" StylesheetTheme="White" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
	<h1>Product Categories</h1>
	<asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
		AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CategoryID"
		DataSourceID="SqlDataSource1">
		<Columns>
			<asp:BoundField DataField="CategoryID" HeaderText="CategoryID" InsertVisible="False"
				ReadOnly="True" SortExpression="CategoryID" />
			<asp:BoundField DataField="CategoryName" HeaderText="CategoryName" SortExpression="CategoryName" />
		</Columns>
	</asp:GridView>
	<br />
	<h1>Add Category</h1><br />
	<asp:FormView ID="FormView1" runat="server" DataKeyNames="CategoryID" DataSourceID="SqlDataSource1"
		DefaultMode="Insert">
		 <InsertItemTemplate>
			 CategoryName:
			 <asp:TextBox ID="CategoryNameTextBox" runat="server" Text='<%#Bind("CategoryName")%>'>
			 </asp:TextBox><br />
			 <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert"
				 Text="Insert">
			 </asp:LinkButton>
		</InsertItemTemplate>
		<EditItemTemplate>
			CategoryID:
			<asp:Label ID="CategoryIDLabel1" runat="server" Text='<%#Eval("CategoryID")%>'>
			</asp:Label><br />
			CategoryName:
			<asp:TextBox ID="CategoryNameTextBox" runat="server" Text='<%#Bind("CategoryName")%>'>
			</asp:TextBox><br />
			<asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update"
				Text="Update">
			</asp:LinkButton>
			<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel"
				Text="Cancel">
			</asp:LinkButton>
		</EditItemTemplate>
		<ItemTemplate>
			CategoryID:
			<asp:Label ID="CategoryIDLabel" runat="server" Text='<%#Eval("CategoryID")%>'>
			</asp:Label><br />
			CategoryName:
			<asp:Label ID="CategoryNameLabel" runat="server" Text='<%#Bind("CategoryName")%>'>
			</asp:Label><br />
		</ItemTemplate>
	</asp:FormView>
	<br />
	<br />
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
		SelectCommand="SELECT [CategoryID], [CategoryName] FROM [CMRC_Categories]" 
		DeleteCommand="DELETE FROM [CMRC_Categories] WHERE [CategoryID] = @CategoryID" 
		InsertCommand="INSERT INTO [CMRC_Categories] ([CategoryName]) VALUES (@CategoryName)" 
		UpdateCommand="UPDATE [CMRC_Categories] SET [CategoryName] = @CategoryName WHERE [CategoryID] = @CategoryID">
		<DeleteParameters>
			<asp:Parameter Name="CategoryID" Type="Int32" />
		</DeleteParameters>
		<UpdateParameters>
			<asp:Parameter Name="CategoryName" Type="String" />
			<asp:Parameter Name="CategoryID" Type="Int32" />
		</UpdateParameters>
		<InsertParameters>
			<asp:Parameter Name="CategoryName" Type="String" />
		</InsertParameters>
	</asp:SqlDataSource>

</asp:Content>

